version: 2

variables:
  update_conda: &update_conda
    run:
      name: Update conda
      command: conda update --yes conda
  install_kipoiseq_deps: &install_kipoiseq_deps
    run:
      name: Install Kipoiseq conda dependencies
      command: conda install --yes -c bioconda pybedtools pyfaidx
  install_git_lfs: &install_git_lfs
    run:
      name: Install git-lfs
      command: conda install --yes -c conda-forge git-lfs
  install_pip_deps: &install_pip_deps
    run:
      name: Install pip dependencies
      command: pip install -r app/requirements.txt --ignore-installed
  install_kipoi: &install_kipoi
    run:
      name: Install Kipoi
      command: pip install git+ssh://git@github.com/kipoi/kipoi.git
  install_kipoiseq: &install_kipoiseq
    run:
      name: Install Kipoiseq
      command: pip install git+ssh://git@github.com/kipoi/kipoiseq.git
  install_awscli: &install_awscli
    run:
      name: Install awscli
      command: pip install awscli
  kipoi_ls: &kipoi_ls
    run:
      name: List kipoi packages
      command: kipoi ls

jobs:

  test_build:
    docker:
      - image: continuumio/miniconda3:4.5.12
      # - image: kipoi/miniconda3:4.3.14
    working_directory: ~/repo
    steps:
      - checkout
      - *update_conda
      - *install_kipoi
      - *install_kipoiseq_deps
      - *install_kipoiseq
      - *kipoi_ls
      - *install_pip_deps
      - *install_awscli
      - run:
          name: Build docs
          command: |
            # export FREEZER_BASE_URL=http://kipoi-website.s3-website.eu-central-1.amazonaws.com/test/${CIRCLE_SHA1}/
            export FREEZER_RELATIVE_URLS=True
            python freeze.py
      - run:
          name: Deploy test website to S3
          command: aws s3 sync app/build s3://kipoi-website/test/${CIRCLE_SHA1}/
      - run:
          name: Get website url
          command: echo http://kipoi-website.s3-website.eu-central-1.amazonaws.com/test/${CIRCLE_SHA1}/
          
  build_deploy:
    docker:
      - image: continuumio/miniconda3:4.5.12
      # - image: continuumio/miniconda3:4.3.14
      # - image: continuumio/anaconda3:5.0.1
      # - image: kipoi/miniconda3:4.3.14
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - 60:0f:05:31:12:3d:bc:8b:df:9d:08:da:71:a5:43:b6
      - checkout
      - *update_conda
      - *install_kipoi
      - *install_kipoiseq_deps
      - *install_kipoiseq
      - *kipoi_ls
      - *install_pip_deps
      - run:
          name: Build docs
          command: python freeze.py
      - run:
          name: Deploy docs
          command: .circleci/deploy_docs.bash


workflows:
  version: 2

  # just build
  test-build:
    jobs:
      - test_build:
          filters:
            branches:
              ignore:
                - master
                - setup_deployment
                
  build-n-deploy:
    jobs:
      - build_deploy:
          filters:
            branches:
              only:
                - master
                - setup_deployment

  # nightly
  kipoi-nightly-test:
     triggers:
       - schedule:
           cron: "0 1 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - build_deploy
