version: 2

variables:
  install_gcc: &install_gcc
    run:
      name: Install gcc and g++
      command: |
        apt-get update && apt-get -y install gcc g++
  install_kipoiseq_deps: &install_kipoiseq_deps
    run:
      name: Install Kipoiseq conda dependencies
      command: |
        source activate py310
        conda install --yes -c bioconda cython
        pip install pybedtools pyfaidx pyranges
  install_kipoi-veff2_deps: &install_kipoi-veff2_deps
    run:
      name: Install kipoi-veff2 conda dependencies
      command: |
        source activate py310
        pip install cyvcf2  
  install_git_lfs: &install_git_lfs
    run:
      name: Install git-lfs
      command: |
        source activate py310  
        conda install --yes -c conda-forge git-lfs
  install_pip_deps: &install_pip_deps
    run:
      name: Install pip dependencies
      command: |
        source activate py310
        pip install -r app/requirements.txt
  install_kipoi: &install_kipoi
    run:
      name: Install Kipoi
      command: |
        conda create -n py310 python=3.10
        source activate py310
        conda install --yes -c conda-forge hdf5 pkgconfig
        pip install git+ssh://git@github.com/kipoi/kipoi.git
  install_kipoiseq: &install_kipoiseq
    run:
      name: Install Kipoiseq
      command: |
        source activate py310
        pip install git+ssh://git@github.com/kipoi/kipoiseq.git
  install_kipoi-veff2: &install_kipoi-veff2
    run:
      name: Install kipoi-veff2
      command: |
          source activate py310
          pip install git+ssh://git@github.com/kipoi/kipoi-veff2.git
  install_awscli: &install_awscli
    run:
      name: Install awscli
      command: |
        source activate py310
        pip install awscli
  kipoi_ls: &kipoi_ls
    run:
      name: List kipoi packages
      command: |
        source activate py310
        kipoi ls

jobs:

  test_build:
    docker:
      - image: continuumio/miniconda3:latest
      # - image: kipoi/miniconda3:4.3.14
    resource_class: medium
    working_directory: ~/repo
    steps:
      - checkout
      - *install_gcc
      - *install_kipoi
      - *install_kipoiseq_deps
      - *install_kipoiseq
      - *install_kipoi-veff2_deps
      - *install_kipoi-veff2
      - *kipoi_ls
      - *install_pip_deps
      - *install_awscli
      - run:
          name: Build docs
          command: |
            # export FREEZER_BASE_URL=http://kipoi-website.s3-website.eu-central-1.amazonaws.com/test/${CIRCLE_SHA1}/
            export FREEZER_RELATIVE_URLS=True
            source activate py310
            python freeze.py
      - run:
          name: Deploy test website to S3
          command: |
            source activate py310
            aws s3 sync app/build s3://kipoi-website/test/${CIRCLE_SHA1}/
      - run:
          name: Get website url
          command: echo http://kipoi-website.s3-website.eu-central-1.amazonaws.com/test/${CIRCLE_SHA1}/
          
  build_deploy:
    docker:
      - image: continuumio/miniconda3:latest
      # - image: continuumio/miniconda3:4.3.14
      # - image: continuumio/anaconda3:5.0.1
      # - image: kipoi/miniconda3:4.3.14
    resource_class: medium
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - 60:0f:05:31:12:3d:bc:8b:df:9d:08:da:71:a5:43:b6
      - checkout
      - *install_gcc
      - *install_kipoi
      - *install_kipoiseq_deps
      - *install_kipoiseq
      - *install_kipoi-veff2_deps
      - *install_kipoi-veff2
      - *kipoi_ls
      - *install_pip_deps
      - run:
          name: Build docs
          command: |
            source activate py310
            python freeze.py
      - run:
          name: Deploy docs
          command: .circleci/deploy_docs.bash


workflows:
  version: 2

  # just build
  test-build:
    jobs:
      - test_build:
          filters:
            branches:
              ignore:
                - master
                - setup_deployment
                
  build-n-deploy:
    jobs:
      - build_deploy:
          filters:
            branches:
              only:
                - master
                - setup_deployment

  # nightly
  kipoi-nightly-test:
     triggers:
       - schedule:
           cron: "0 1 * * *"
           filters:
             branches:
               only:
                 - master

     jobs:
       - test_build
       - build_deploy
